import base64
import os
import platform
import tempfile
from pathlib import Path

# Base64-encoded ICO file (Windows)
ICON_ICO_B64 = '''
AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAMMOAADDDgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAwZ+DUcGfg//Bn4P/wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4P/
wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4NRAAAAAAAAAAAAAAAAx6SIUMekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAAAAAAAAAAAMekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/
x6SI/8ekiP8AAAAAAAAAAAAAAADHpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/AAAAAAAA
AAAAAAAAx6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAAAAAAAAAAAMekiP/HpIj/
x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP8AAAAAAAAAAAAAAADHpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/AAAAAAAAAAAAAAAAx6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/
x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAA
AAAAAAAAAMekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP8AAAAAAAAAAAAAAADNqo7/zaqO
/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/
zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/AAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/N
qo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82q
jv/Nqo7/zaqO/wAAAAAAAAAAAAAAAM2qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO
/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv8AAAAA
AAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/N
qo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/
zaqO/82qjv/Nqo7/zaqO/82qjv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMUyyuAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjFMsrgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIxTLK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjFMsrgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA=
'''

# Base64-encoded ICNS file (macOS)
ICON_ICNS_B64 = '''
AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAMMOAADDDgAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAwZ+DUcGfg//Bn4P/wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4P/
wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4P/wZ+D/8Gfg//Bn4NRAAAAAAAAAAAAAAAAx6SIUMekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAAAAAAAAAAAMekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/
x6SI/8ekiP8AAAAAAAAAAAAAAADHpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/AAAAAAAA
AAAAAAAAx6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAAAAAAAAAAAMekiP/HpIj/
x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/H
pIj/x6SI/8ekiP/HpIj/x6SI/8ekiP8AAAAAAAAAAAAAAADHpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI
/8ekiP/HpIj/AAAAAAAAAAAAAAAAx6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/
x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/wAAAAAA
AAAAAAAAAMekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ek
iP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP/HpIj/x6SI/8ekiP8AAAAAAAAAAAAAAADNqo7/zaqO
/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/
zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/AAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/N
qo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82q
jv/Nqo7/zaqO/wAAAAAAAAAAAAAAAM2qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO
/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv8AAAAA
AAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/N
qo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAzaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO/82qjv/Nqo7/zaqO
/82qjv/Nqo7/zaqO/82qjv8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA
YDm0gGA5tIBgObSAYDm0gGA5tIBgObSAYDm0gGA5tIBgObSAYDm0gGA5tIBgObSAYDm0gGA5tIBg
ObSAYDm0gGA5tIBgObSAYDm0gGA5tIBgObSAYDm0gGA5tAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIxTLK4AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjFMsrgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AIxTLK4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjFMsrgAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAA=
'''

def get_app_icon():
    """Create and return a path to the appropriate app icon for the platform"""
    system = platform.system()
    
    if system == 'Windows':
        # For Windows, create and return an .ico file
        icon_data = base64.b64decode(ICON_ICO_B64)
        icon_path = os.path.join(tempfile.gettempdir(), 'app_icon.ico')
        with open(icon_path, 'wb') as f:
            f.write(icon_data)
        return icon_path
        
    elif system == 'Darwin':
        # For macOS, create and return an .icns file
        icon_data = base64.b64decode(ICON_ICNS_B64)
        icon_path = os.path.join(tempfile.gettempdir(), 'app_icon.icns')
        with open(icon_path, 'wb') as f:
            f.write(icon_data)
        return icon_path
        
    else:
        # For Linux, create a .png file (typical for Linux systems)
        # For simplicity, we'll reuse one of the existing icons
        icon_data = base64.b64decode(ICON_ICO_B64)  # Can be adjusted if needed
        icon_path = os.path.join(tempfile.gettempdir(), 'app_icon.png')
        with open(icon_path, 'wb') as f:
            f.write(icon_data)
        return icon_path

# Save platform-specific icon files to the current directory for GitHub Actions
def save_icons_for_build():
    # Save Windows icon
    icon_data = base64.b64decode(ICON_ICO_B64)
    with open('app_icon.ico', 'wb') as f:
        f.write(icon_data)
        
    # Save macOS icon
    icon_data = base64.b64decode(ICON_ICNS_B64)
    with open('app_icon.icns', 'wb') as f:
        f.write(icon_data)
        
    print("Icons saved for build process")
